name: Check Melon Ticket - 213498

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Check Ticket Availability
        uses: mooyoul/melon-ticket-actions@v1.1.0[cite: 1]
        with:
          product-id: '213498'
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}[cite: 1]
